services:
  core-service:
    container_name: core-service
    build:
      context: ./
      dockerfile: ./docker/core/Dockerfile
    restart: unless-stopped

  date-service:
    container_name: date-service
    build:
      context: ./
      dockerfile: ./docker/date/Dockerfile
    restart: unless-stopped

  storage-service:
    container_name: storage-service
    environment:
      - DB_ADDR=database:5432
      - DB_USER=${DB_USERNAME}
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    build:
      context: ./
      dockerfile: ./docker/storage/Dockerfile
    restart: unless-stopped

  balancer:
    container_name: balancer
    image: nginx:mainline-alpine3.21
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - core-service
      - date-service
      - storage-service
    restart: unless-stopped

  database:
    container_name: database
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME -d $DB_NAME"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  migrations:
    container_name: migrations
    image: migrate/migrate
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://$DB_USERNAME:$DB_PASSWORD@database:5432/$DB_NAME?sslmode=disable",
        "up"
      ]

volumes:
  database-data:
